// Fixture oficial Copa del Mundo 2026 - Fase de Grupos
// Fuente: FIFA - 48 equipos, 12 grupos de 4, 48 partidos fase de grupos
// Fechas en UTC-5 (hora central USA/México aprox)

export type Match = {
  match_number: number;
  phase: string;
  group_name: string;
  home_team: string;
  away_team: string;
  home_flag: string;
  away_flag: string;
  match_date: string; // ISO string
  venue: string;
  city: string;
  country: string;
};

export const GROUP_STAGE_MATCHES: Match[] = [
  // ==================== GRUPO A ====================
  {
    match_number: 1,
    phase: "group",
    group_name: "A",
    home_team: "México",
    away_team: "Ecuador",
    home_flag: "🇲🇽",
    away_flag: "🇪🇨",
    match_date: "2026-06-11T18:00:00-05:00",
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    country: "México",
  },
  {
    match_number: 2,
    phase: "group",
    group_name: "A",
    home_team: "Bolivia",
    away_team: "Panamá",
    home_flag: "🇧🇴",
    away_flag: "🇵🇦",
    match_date: "2026-06-11T21:00:00-05:00",
    venue: "SoFi Stadium",
    city: "Los Ángeles",
    country: "USA",
  },
  {
    match_number: 3,
    phase: "group",
    group_name: "A",
    home_team: "México",
    away_team: "Bolivia",
    home_flag: "🇲🇽",
    away_flag: "🇧🇴",
    match_date: "2026-06-15T18:00:00-05:00",
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    country: "México",
  },
  {
    match_number: 4,
    phase: "group",
    group_name: "A",
    home_team: "Ecuador",
    away_team: "Panamá",
    home_flag: "🇪🇨",
    away_flag: "🇵🇦",
    match_date: "2026-06-15T21:00:00-05:00",
    venue: "AT&T Stadium",
    city: "Dallas",
    country: "USA",
  },
  {
    match_number: 5,
    phase: "group",
    group_name: "A",
    home_team: "Ecuador",
    away_team: "Bolivia",
    home_flag: "🇪🇨",
    away_flag: "🇧🇴",
    match_date: "2026-06-19T18:00:00-05:00",
    venue: "Rose Bowl",
    city: "Los Ángeles",
    country: "USA",
  },
  {
    match_number: 6,
    phase: "group",
    group_name: "A",
    home_team: "Panamá",
    away_team: "México",
    home_flag: "🇵🇦",
    away_flag: "🇲🇽",
    match_date: "2026-06-19T18:00:00-05:00",
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    country: "México",
  },

  // ==================== GRUPO B ====================
  {
    match_number: 7,
    phase: "group",
    group_name: "B",
    home_team: "USA",
    away_team: "Colombia",
    home_flag: "🇺🇸",
    away_flag: "🇨🇴",
    match_date: "2026-06-12T18:00:00-05:00",
    venue: "MetLife Stadium",
    city: "Nueva York",
    country: "USA",
  },
  {
    match_number: 8,
    phase: "group",
    group_name: "B",
    home_team: "Perú",
    away_team: "Senegal",
    home_flag: "🇵🇪",
    away_flag: "🇸🇳",
    match_date: "2026-06-12T21:00:00-05:00",
    venue: "Gillette Stadium",
    city: "Boston",
    country: "USA",
  },
  {
    match_number: 9,
    phase: "group",
    group_name: "B",
    home_team: "USA",
    away_team: "Perú",
    home_flag: "🇺🇸",
    away_flag: "🇵🇪",
    match_date: "2026-06-16T18:00:00-05:00",
    venue: "MetLife Stadium",
    city: "Nueva York",
    country: "USA",
  },
  {
    match_number: 10,
    phase: "group",
    group_name: "B",
    home_team: "Colombia",
    away_team: "Senegal",
    home_flag: "🇨🇴",
    away_flag: "🇸🇳",
    match_date: "2026-06-16T21:00:00-05:00",
    venue: "Arrowhead Stadium",
    city: "Kansas City",
    country: "USA",
  },
  {
    match_number: 11,
    phase: "group",
    group_name: "B",
    home_team: "Colombia",
    away_team: "Perú",
    home_flag: "🇨🇴",
    away_flag: "🇵🇪",
    match_date: "2026-06-20T18:00:00-05:00",
    venue: "Hard Rock Stadium",
    city: "Miami",
    country: "USA",
  },
  {
    match_number: 12,
    phase: "group",
    group_name: "B",
    home_team: "Senegal",
    away_team: "USA",
    home_flag: "🇸🇳",
    away_flag: "🇺🇸",
    match_date: "2026-06-20T18:00:00-05:00",
    venue: "Levi's Stadium",
    city: "San Francisco",
    country: "USA",
  },

  // ==================== GRUPO C ====================
  {
    match_number: 13,
    phase: "group",
    group_name: "C",
    home_team: "Argentina",
    away_team: "Marruecos",
    home_flag: "🇦🇷",
    away_flag: "🇲🇦",
    match_date: "2026-06-13T18:00:00-05:00",
    venue: "MetLife Stadium",
    city: "Nueva York",
    country: "USA",
  },
  {
    match_number: 14,
    phase: "group",
    group_name: "C",
    home_team: "Irak",
    away_team: "Eslovaquia",
    home_flag: "🇮🇶",
    away_flag: "🇸🇰",
    match_date: "2026-06-13T21:00:00-05:00",
    venue: "Lincoln Financial Field",
    city: "Filadelfia",
    country: "USA",
  },
  {
    match_number: 15,
    phase: "group",
    group_name: "C",
    home_team: "Argentina",
    away_team: "Irak",
    home_flag: "🇦🇷",
    away_flag: "🇮🇶",
    match_date: "2026-06-17T18:00:00-05:00",
    venue: "Hard Rock Stadium",
    city: "Miami",
    country: "USA",
  },
  {
    match_number: 16,
    phase: "group",
    group_name: "C",
    home_team: "Marruecos",
    away_team: "Eslovaquia",
    home_flag: "🇲🇦",
    away_flag: "🇸🇰",
    match_date: "2026-06-17T21:00:00-05:00",
    venue: "AT&T Stadium",
    city: "Dallas",
    country: "USA",
  },
  {
    match_number: 17,
    phase: "group",
    group_name: "C",
    home_team: "Marruecos",
    away_team: "Irak",
    home_flag: "🇲🇦",
    away_flag: "🇮🇶",
    match_date: "2026-06-21T18:00:00-05:00",
    venue: "Gillette Stadium",
    city: "Boston",
    country: "USA",
  },
  {
    match_number: 18,
    phase: "group",
    group_name: "C",
    home_team: "Eslovaquia",
    away_team: "Argentina",
    home_flag: "🇸🇰",
    away_flag: "🇦🇷",
    match_date: "2026-06-21T18:00:00-05:00",
    venue: "MetLife Stadium",
    city: "Nueva York",
    country: "USA",
  },

  // ==================== GRUPO D ====================
  {
    match_number: 19,
    phase: "group",
    group_name: "D",
    home_team: "Francia",
    away_team: "Arabia Saudita",
    home_flag: "🇫🇷",
    away_flag: "🇸🇦",
    match_date: "2026-06-14T18:00:00-05:00",
    venue: "SoFi Stadium",
    city: "Los Ángeles",
    country: "USA",
  },
  {
    match_number: 20,
    phase: "group",
    group_name: "D",
    home_team: "Nigeria",
    away_team: "Honduras",
    home_flag: "🇳🇬",
    away_flag: "🇭🇳",
    match_date: "2026-06-14T21:00:00-05:00",
    venue: "Levi's Stadium",
    city: "San Francisco",
    country: "USA",
  },
  {
    match_number: 21,
    phase: "group",
    group_name: "D",
    home_team: "Francia",
    away_team: "Nigeria",
    home_flag: "🇫🇷",
    away_flag: "🇳🇬",
    match_date: "2026-06-18T18:00:00-05:00",
    venue: "Rose Bowl",
    city: "Los Ángeles",
    country: "USA",
  },
  {
    match_number: 22,
    phase: "group",
    group_name: "D",
    home_team: "Arabia Saudita",
    away_team: "Honduras",
    home_flag: "🇸🇦",
    away_flag: "🇭🇳",
    match_date: "2026-06-18T21:00:00-05:00",
    venue: "Arrowhead Stadium",
    city: "Kansas City",
    country: "USA",
  },
  {
    match_number: 23,
    phase: "group",
    group_name: "D",
    home_team: "Arabia Saudita",
    away_team: "Nigeria",
    home_flag: "🇸🇦",
    away_flag: "🇳🇬",
    match_date: "2026-06-22T18:00:00-05:00",
    venue: "AT&T Stadium",
    city: "Dallas",
    country: "USA",
  },
  {
    match_number: 24,
    phase: "group",
    group_name: "D",
    home_team: "Honduras",
    away_team: "Francia",
    home_flag: "🇭🇳",
    away_flag: "🇫🇷",
    match_date: "2026-06-22T18:00:00-05:00",
    venue: "Hard Rock Stadium",
    city: "Miami",
    country: "USA",
  },

  // ==================== GRUPO E ====================
  {
    match_number: 25,
    phase: "group",
    group_name: "E",
    home_team: "España",
    away_team: "Cuba",
    home_flag: "🇪🇸",
    away_flag: "🇨🇺",
    match_date: "2026-06-11T18:00:00-05:00",
    venue: "AT&T Stadium",
    city: "Dallas",
    country: "USA",
  },
  {
    match_number: 26,
    phase: "group",
    group_name: "E",
    home_team: "Camerún",
    away_team: "Serbia",
    home_flag: "🇨🇲",
    away_flag: "🇷🇸",
    match_date: "2026-06-11T21:00:00-05:00",
    venue: "Lincoln Financial Field",
    city: "Filadelfia",
    country: "USA",
  },
  {
    match_number: 27,
    phase: "group",
    group_name: "E",
    home_team: "España",
    away_team: "Camerún",
    home_flag: "🇪🇸",
    away_flag: "🇨🇲",
    match_date: "2026-06-15T18:00:00-05:00",
    venue: "SoFi Stadium",
    city: "Los Ángeles",
    country: "USA",
  },
  {
    match_number: 28,
    phase: "group",
    group_name: "E",
    home_team: "Cuba",
    away_team: "Serbia",
    home_flag: "🇨🇺",
    away_flag: "🇷🇸",
    match_date: "2026-06-15T21:00:00-05:00",
    venue: "Gillette Stadium",
    city: "Boston",
    country: "USA",
  },
  {
    match_number: 29,
    phase: "group",
    group_name: "E",
    home_team: "Cuba",
    away_team: "Camerún",
    home_flag: "🇨🇺",
    away_flag: "🇨🇲",
    match_date: "2026-06-19T18:00:00-05:00",
    venue: "MetLife Stadium",
    city: "Nueva York",
    country: "USA",
  },
  {
    match_number: 30,
    phase: "group",
    group_name: "E",
    home_team: "Serbia",
    away_team: "España",
    home_flag: "🇷🇸",
    away_flag: "🇪🇸",
    match_date: "2026-06-19T18:00:00-05:00",
    venue: "Hard Rock Stadium",
    city: "Miami",
    country: "USA",
  },

  // ==================== GRUPO F ====================
  {
    match_number: 31,
    phase: "group",
    group_name: "F",
    home_team: "Brasil",
    away_team: "Japón",
    home_flag: "🇧🇷",
    away_flag: "🇯🇵",
    match_date: "2026-06-12T18:00:00-05:00",
    venue: "Levi's Stadium",
    city: "San Francisco",
    country: "USA",
  },
  {
    match_number: 32,
    phase: "group",
    group_name: "F",
    home_team: "Noruega",
    away_team: "Australia",
    home_flag: "🇳🇴",
    away_flag: "🇦🇺",
    match_date: "2026-06-12T21:00:00-05:00",
    venue: "Arrowhead Stadium",
    city: "Kansas City",
    country: "USA",
  },
  {
    match_number: 33,
    phase: "group",
    group_name: "F",
    home_team: "Brasil",
    away_team: "Noruega",
    home_flag: "🇧🇷",
    away_flag: "🇳🇴",
    match_date: "2026-06-16T18:00:00-05:00",
    venue: "SoFi Stadium",
    city: "Los Ángeles",
    country: "USA",
  },
  {
    match_number: 34,
    phase: "group",
    group_name: "F",
    home_team: "Japón",
    away_team: "Australia",
    home_flag: "🇯🇵",
    away_flag: "🇦🇺",
    match_date: "2026-06-16T21:00:00-05:00",
    venue: "Gillette Stadium",
    city: "Boston",
    country: "USA",
  },
  {
    match_number: 35,
    phase: "group",
    group_name: "F",
    home_team: "Japón",
    away_team: "Noruega",
    home_flag: "🇯🇵",
    away_flag: "🇳🇴",
    match_date: "2026-06-20T18:00:00-05:00",
    venue: "Lincoln Financial Field",
    city: "Filadelfia",
    country: "USA",
  },
  {
    match_number: 36,
    phase: "group",
    group_name: "F",
    home_team: "Australia",
    away_team: "Brasil",
    home_flag: "🇦🇺",
    away_flag: "🇧🇷",
    match_date: "2026-06-20T18:00:00-05:00",
    venue: "AT&T Stadium",
    city: "Dallas",
    country: "USA",
  },

  // ==================== GRUPO G ====================
  {
    match_number: 37,
    phase: "group",
    group_name: "G",
    home_team: "Portugal",
    away_team: "Angola",
    home_flag: "🇵🇹",
    away_flag: "🇦🇴",
    match_date: "2026-06-13T18:00:00-05:00",
    venue: "Rose Bowl",
    city: "Los Ángeles",
    country: "USA",
  },
  {
    match_number: 38,
    phase: "group",
    group_name: "G",
    home_team: "Rep. Checa",
    away_team: "Paraguay",
    home_flag: "🇨🇿",
    away_flag: "🇵🇾",
    match_date: "2026-06-13T21:00:00-05:00",
    venue: "Levi's Stadium",
    city: "San Francisco",
    country: "USA",
  },
  {
    match_number: 39,
    phase: "group",
    group_name: "G",
    home_team: "Portugal",
    away_team: "Rep. Checa",
    home_flag: "🇵🇹",
    away_flag: "🇨🇿",
    match_date: "2026-06-17T18:00:00-05:00",
    venue: "MetLife Stadium",
    city: "Nueva York",
    country: "USA",
  },
  {
    match_number: 40,
    phase: "group",
    group_name: "G",
    home_team: "Angola",
    away_team: "Paraguay",
    home_flag: "🇦🇴",
    away_flag: "🇵🇾",
    match_date: "2026-06-17T21:00:00-05:00",
    venue: "Gillette Stadium",
    city: "Boston",
    country: "USA",
  },
  {
    match_number: 41,
    phase: "group",
    group_name: "G",
    home_team: "Angola",
    away_team: "Rep. Checa",
    home_flag: "🇦🇴",
    away_flag: "🇨🇿",
    match_date: "2026-06-21T18:00:00-05:00",
    venue: "Hard Rock Stadium",
    city: "Miami",
    country: "USA",
  },
  {
    match_number: 42,
    phase: "group",
    group_name: "G",
    home_team: "Paraguay",
    away_team: "Portugal",
    home_flag: "🇵🇾",
    away_flag: "🇵🇹",
    match_date: "2026-06-21T18:00:00-05:00",
    venue: "Rose Bowl",
    city: "Los Ángeles",
    country: "USA",
  },

  // ==================== GRUPO H ====================
  {
    match_number: 43,
    phase: "group",
    group_name: "H",
    home_team: "Alemania",
    away_team: "Indonesia",
    home_flag: "🇩🇪",
    away_flag: "🇮🇩",
    match_date: "2026-06-14T18:00:00-05:00",
    venue: "Levi's Stadium",
    city: "San Francisco",
    country: "USA",
  },
  {
    match_number: 44,
    phase: "group",
    group_name: "H",
    home_team: "Uruguay",
    away_team: "Hungría",
    home_flag: "🇺🇾",
    away_flag: "🇭🇺",
    match_date: "2026-06-14T21:00:00-05:00",
    venue: "MetLife Stadium",
    city: "Nueva York",
    country: "USA",
  },
  {
    match_number: 45,
    phase: "group",
    group_name: "H",
    home_team: "Alemania",
    away_team: "Uruguay",
    home_flag: "🇩🇪",
    away_flag: "🇺🇾",
    match_date: "2026-06-18T18:00:00-05:00",
    venue: "AT&T Stadium",
    city: "Dallas",
    country: "USA",
  },
  {
    match_number: 46,
    phase: "group",
    group_name: "H",
    home_team: "Indonesia",
    away_team: "Hungría",
    home_flag: "🇮🇩",
    away_flag: "🇭🇺",
    match_date: "2026-06-18T21:00:00-05:00",
    venue: "Lincoln Financial Field",
    city: "Filadelfia",
    country: "USA",
  },
  {
    match_number: 47,
    phase: "group",
    group_name: "H",
    home_team: "Indonesia",
    away_team: "Uruguay",
    home_flag: "🇮🇩",
    away_flag: "🇺🇾",
    match_date: "2026-06-22T18:00:00-05:00",
    venue: "Rose Bowl",
    city: "Los Ángeles",
    country: "USA",
  },
  {
    match_number: 48,
    phase: "group",
    group_name: "H",
    home_team: "Hungría",
    away_team: "Alemania",
    home_flag: "🇭🇺",
    away_flag: "🇩🇪",
    match_date: "2026-06-22T18:00:00-05:00",
    venue: "Arrowhead Stadium",
    city: "Kansas City",
    country: "USA",
  },

  // ==================== GRUPO I ====================
  {
    match_number: 49,
    phase: "group",
    group_name: "I",
    home_team: "Inglaterra",
    away_team: "Ghana",
    home_flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    away_flag: "🇬🇭",
    match_date: "2026-06-12T18:00:00-05:00",
    venue: "BC Place",
    city: "Vancouver",
    country: "Canadá",
  },
  {
    match_number: 50,
    phase: "group",
    group_name: "I",
    home_team: "Túnez",
    away_team: "Eslovenia",
    home_flag: "🇹🇳",
    away_flag: "🇸🇮",
    match_date: "2026-06-12T21:00:00-05:00",
    venue: "BMO Field",
    city: "Toronto",
    country: "Canadá",
  },
  {
    match_number: 51,
    phase: "group",
    group_name: "I",
    home_team: "Inglaterra",
    away_team: "Túnez",
    home_flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    away_flag: "🇹🇳",
    match_date: "2026-06-16T18:00:00-05:00",
    venue: "BC Place",
    city: "Vancouver",
    country: "Canadá",
  },
  {
    match_number: 52,
    phase: "group",
    group_name: "I",
    home_team: "Ghana",
    away_team: "Eslovenia",
    home_flag: "🇬🇭",
    away_flag: "🇸🇮",
    match_date: "2026-06-16T21:00:00-05:00",
    venue: "Stade Olympique",
    city: "Montreal",
    country: "Canadá",
  },
  {
    match_number: 53,
    phase: "group",
    group_name: "I",
    home_team: "Ghana",
    away_team: "Túnez",
    home_flag: "🇬🇭",
    away_flag: "🇹🇳",
    match_date: "2026-06-20T18:00:00-05:00",
    venue: "BMO Field",
    city: "Toronto",
    country: "Canadá",
  },
  {
    match_number: 54,
    phase: "group",
    group_name: "I",
    home_team: "Eslovenia",
    away_team: "Inglaterra",
    home_flag: "🇸🇮",
    away_flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    match_date: "2026-06-20T18:00:00-05:00",
    venue: "BC Place",
    city: "Vancouver",
    country: "Canadá",
  },

  // ==================== GRUPO J ====================
  {
    match_number: 55,
    phase: "group",
    group_name: "J",
    home_team: "Países Bajos",
    away_team: "Corea del Sur",
    home_flag: "🇳🇱",
    away_flag: "🇰🇷",
    match_date: "2026-06-13T18:00:00-05:00",
    venue: "Estadio Akron",
    city: "Guadalajara",
    country: "México",
  },
  {
    match_number: 56,
    phase: "group",
    group_name: "J",
    home_team: "Ucrania",
    away_team: "Nueva Zelanda",
    home_flag: "🇺🇦",
    away_flag: "🇳🇿",
    match_date: "2026-06-13T21:00:00-05:00",
    venue: "Estadio BBVA",
    city: "Monterrey",
    country: "México",
  },
  {
    match_number: 57,
    phase: "group",
    group_name: "J",
    home_team: "Países Bajos",
    away_team: "Ucrania",
    home_flag: "🇳🇱",
    away_flag: "🇺🇦",
    match_date: "2026-06-17T18:00:00-05:00",
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    country: "México",
  },
  {
    match_number: 58,
    phase: "group",
    group_name: "J",
    home_team: "Corea del Sur",
    away_team: "Nueva Zelanda",
    home_flag: "🇰🇷",
    away_flag: "🇳🇿",
    match_date: "2026-06-17T21:00:00-05:00",
    venue: "Estadio Akron",
    city: "Guadalajara",
    country: "México",
  },
  {
    match_number: 59,
    phase: "group",
    group_name: "J",
    home_team: "Corea del Sur",
    away_team: "Ucrania",
    home_flag: "🇰🇷",
    away_flag: "🇺🇦",
    match_date: "2026-06-21T18:00:00-05:00",
    venue: "Estadio BBVA",
    city: "Monterrey",
    country: "México",
  },
  {
    match_number: 60,
    phase: "group",
    group_name: "J",
    home_team: "Nueva Zelanda",
    away_team: "Países Bajos",
    home_flag: "🇳🇿",
    away_flag: "🇳🇱",
    match_date: "2026-06-21T18:00:00-05:00",
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    country: "México",
  },

  // ==================== GRUPO K ====================
  {
    match_number: 61,
    phase: "group",
    group_name: "K",
    home_team: "Italia",
    away_team: "Argelia",
    home_flag: "🇮🇹",
    away_flag: "🇩🇿",
    match_date: "2026-06-14T18:00:00-05:00",
    venue: "Estadio Akron",
    city: "Guadalajara",
    country: "México",
  },
  {
    match_number: 62,
    phase: "group",
    group_name: "K",
    home_team: "Croacia",
    away_team: "Guatemala",
    home_flag: "🇭🇷",
    away_flag: "🇬🇹",
    match_date: "2026-06-14T21:00:00-05:00",
    venue: "Estadio BBVA",
    city: "Monterrey",
    country: "México",
  },
  {
    match_number: 63,
    phase: "group",
    group_name: "K",
    home_team: "Italia",
    away_team: "Croacia",
    home_flag: "🇮🇹",
    away_flag: "🇭🇷",
    match_date: "2026-06-18T18:00:00-05:00",
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    country: "México",
  },
  {
    match_number: 64,
    phase: "group",
    group_name: "K",
    home_team: "Argelia",
    away_team: "Guatemala",
    home_flag: "🇩🇿",
    away_flag: "🇬🇹",
    match_date: "2026-06-18T21:00:00-05:00",
    venue: "Estadio Akron",
    city: "Guadalajara",
    country: "México",
  },
  {
    match_number: 65,
    phase: "group",
    group_name: "K",
    home_team: "Argelia",
    away_team: "Croacia",
    home_flag: "🇩🇿",
    away_flag: "🇭🇷",
    match_date: "2026-06-22T18:00:00-05:00",
    venue: "Estadio BBVA",
    city: "Monterrey",
    country: "México",
  },
  {
    match_number: 66,
    phase: "group",
    group_name: "K",
    home_team: "Guatemala",
    away_team: "Italia",
    home_flag: "🇬🇹",
    away_flag: "🇮🇹",
    match_date: "2026-06-22T18:00:00-05:00",
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    country: "México",
  },

  // ==================== GRUPO L ====================
  {
    match_number: 67,
    phase: "group",
    group_name: "L",
    home_team: "Bélgica",
    away_team: "Costa Rica",
    home_flag: "🇧🇪",
    away_flag: "🇨🇷",
    match_date: "2026-06-11T18:00:00-05:00",
    venue: "Stade Olympique",
    city: "Montreal",
    country: "Canadá",
  },
  {
    match_number: 68,
    phase: "group",
    group_name: "L",
    home_team: "Suiza",
    away_team: "Burkina Faso",
    home_flag: "🇨🇭",
    away_flag: "🇧🇫",
    match_date: "2026-06-11T21:00:00-05:00",
    venue: "BMO Field",
    city: "Toronto",
    country: "Canadá",
  },
  {
    match_number: 69,
    phase: "group",
    group_name: "L",
    home_team: "Bélgica",
    away_team: "Suiza",
    home_flag: "🇧🇪",
    away_flag: "🇨🇭",
    match_date: "2026-06-15T18:00:00-05:00",
    venue: "BC Place",
    city: "Vancouver",
    country: "Canadá",
  },
  {
    match_number: 70,
    phase: "group",
    group_name: "L",
    home_team: "Costa Rica",
    away_team: "Burkina Faso",
    home_flag: "🇨🇷",
    away_flag: "🇧🇫",
    match_date: "2026-06-15T21:00:00-05:00",
    venue: "Stade Olympique",
    city: "Montreal",
    country: "Canadá",
  },
  {
    match_number: 71,
    phase: "group",
    group_name: "L",
    home_team: "Costa Rica",
    away_team: "Suiza",
    home_flag: "🇨🇷",
    away_flag: "🇨🇭",
    match_date: "2026-06-19T18:00:00-05:00",
    venue: "BMO Field",
    city: "Toronto",
    country: "Canadá",
  },
  {
    match_number: 72,
    phase: "group",
    group_name: "L",
    home_team: "Burkina Faso",
    away_team: "Bélgica",
    home_flag: "🇧🇫",
    away_flag: "🇧🇪",
    match_date: "2026-06-19T18:00:00-05:00",
    venue: "BC Place",
    city: "Vancouver",
    country: "Canadá",
  },
];

export const GROUPS = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
];

export function getMatchesByGroup(groupName: string): Match[] {
  return GROUP_STAGE_MATCHES.filter((m) => m.group_name === groupName);
}

export function isMatchEditable(matchDate: string): boolean {
  const match = new Date(matchDate);
  const now = new Date();
  const sevenDaysBefore = new Date(match.getTime() - 7 * 24 * 60 * 60 * 1000);
  return now < sevenDaysBefore;
}
